### ISSUE TITLE
Update the GH action?

### ISSUE THREAD

**Issue by apreshill** [rstudio/quillt#33]
Hi @cderv -

Noticing this has been added to some GH actions:

https://github.com/rstudio/flexdashboard/blob/b69a37351f89eb1876309b055bc21597ba40d0e2/.github/workflows/pkgdown.yaml#L63-L69

https://github.com/rstudio/gradethis/blob/ced55418f79ba965eb83fbc437d7d875c1c9b528/.github/workflows/pkgdown.yaml#L61-L72

Do we need to update the built in GH action template?

**Comment by gadenbuie** [comment]
The extra step is no longer required since after https://github.com/r-lib/pkgdown/pull/1395 pkgdown should now error on CI (in GHA) when topics are missing.
