### ISSUE TITLE
check sharing images

### ISSUE THREAD

**Issue by apreshill** [rstudio/quillt#8]
just noticed with Garrick in testing that all opengraph social cards are broken, looks like a pkgdown bug, filing here so I don't forget to re-check this!

**Comment by cderv** [comment]
I tested on https://cards-dev.twitter.com/validator and it seems to work ok. 

What is missing ?

**Comment by apreshill** [comment]
Looks like it is working now thanks to @gadenbuie https://github.com/rstudio/quillt/pull/10
